In [162]:
import quandl
import csv


In [163]:
data=quandl.get("LBMA/GOLD", authtoken="ZbxGsy8jS4AxssbNsHEp", start_date="2009-01-01")
csvfile = file('data.csv', 'wb')
writer = csv.writer(csvfile)
writer.writerow(['date', 'price'])
i=1
data_input = [('0','0')]
for data_ in data["USD (AM)"]:
    temp_data = (str(i),str(data_))
    data_input.append(temp_data)
    i = i+1

writer.writerows(data_input)
csvfile.close()

In [164]:
temp =data["USD (AM)"][0]
maxResult = 0
for data_ in data["USD (AM)"]:
    result = data_ 
    if result >= maxResult:
        maxResult = result
    
print maxResult

1896.5


In [1]:
import pandas, matplotlib.pyplot as plt, numpy
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout
from sklearn.preprocessing import MinMaxScaler


Using Theano backend.


In [2]:
# convert an array of values into a dataset matrix
def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset) - look_back - 1):
        a = dataset[i:(i + look_back), 0]
        dataX.append(a)
        dataY.append(dataset[i + look_back, 0])
    return numpy.array(dataX), numpy.array(dataY)

In [165]:

dataframe = pandas.read_csv('data.csv', usecols=[1], engine='python', skipfooter=3)
dataset = dataframe.values
dataset = dataset.astype('float32')

#scale
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)

# split into train and test sets
train_size = int(len(dataset) * 0.95)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size,:], dataset[train_size:len(dataset),:]
print(len(train), len(test))
# reshape into X=t and Y=t+1
look_back = 5
trainX, trainY = create_dataset(train, look_back)
testX, testY = create_dataset(test, look_back)

# reshape input to be [samples, time steps, features]
trainX = numpy.reshape(trainX, (trainX.shape[0], 1, trainX.shape[1]))
testX = numpy.reshape(testX, (testX.shape[0], 1, testX.shape[1]))

# create and fit the LSTM network
model = Sequential()
model.add(LSTM(6, input_dim=look_back))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(trainX, trainY, nb_epoch=100, batch_size=1, verbose=2)


# Estimate model performance
trainScore = model.evaluate(trainX, trainY, verbose=0)
print('Train Score: ', scaler.inverse_transform(numpy.array([[trainScore]])))
testScore = model.evaluate(testX, testY, verbose=0)
print('Test Score: ', scaler.inverse_transform(numpy.array([[testScore]])))

# generate predictions for training
trainPredict = model.predict(trainX)
testPredict = model.predict(testX)

(1924, 102)


KeyboardInterrupt: 

In [14]:
print testPredict
print testPredict.shape

[[ 0.71058971]
 [ 0.71191937]
 [ 0.71227783]
 [ 0.70691961]
 [ 0.70750147]
 [ 0.70729357]
 [ 0.70168209]
 [ 0.70065534]
 [ 0.6980083 ]
 [ 0.69542652]
 [ 0.69129372]
 [ 0.69278461]
 [ 0.70032984]
 [ 0.70267141]
 [ 0.71091092]
 [ 0.71262723]
 [ 0.70754242]
 [ 0.70305544]
 [ 0.70249993]
 [ 0.70017952]
 [ 0.69831371]
 [ 0.69553006]
 [ 0.69520712]
 [ 0.69537163]
 [ 0.6971308 ]
 [ 0.70297253]
 [ 0.70571953]
 [ 0.70639247]
 [ 0.70640343]
 [ 0.70170987]
 [ 0.69893456]
 [ 0.70142537]
 [ 0.69807321]
 [ 0.69319695]
 [ 0.67733395]
 [ 0.67001235]
 [ 0.66443467]
 [ 0.66602665]
 [ 0.66431785]
 [ 0.66342705]
 [ 0.66444826]
 [ 0.66376019]
 [ 0.66216218]
 [ 0.66563696]
 [ 0.6698463 ]
 [ 0.67042702]
 [ 0.66837567]
 [ 0.66922241]
 [ 0.67039734]
 [ 0.67251688]
 [ 0.67110527]
 [ 0.66927826]
 [ 0.67247069]
 [ 0.67746103]
 [ 0.68330228]
 [ 0.6834299 ]
 [ 0.68702525]
 [ 0.68167788]
 [ 0.67902243]
 [ 0.68741822]
 [ 0.67919153]
 [ 0.66635096]
 [ 0.64986062]
 [ 0.64871979]
 [ 0.64763016]
 [ 0.64973402]
 [ 0.63964

In [15]:
0.60694778*1896.5

1151.07646477

In [13]:
#1896.5
print testX
print testX.shape

[[[ 0.70896393  0.70482469  0.7061429   0.71136308  0.70801479]]

 [[ 0.70482469  0.7061429   0.71136308  0.70801479  0.71030849]]

 [[ 0.7061429   0.71136308  0.70801479  0.71030849  0.71017665]]

 [[ 0.71136308  0.70801479  0.71030849  0.71017665  0.70355928]]

 [[ 0.70801479  0.71030849  0.71017665  0.70355928  0.70577383]]

 [[ 0.71030849  0.71017665  0.70355928  0.70577383  0.70514113]]

 [[ 0.71017665  0.70355928  0.70577383  0.70514113  0.6983918 ]]

 [[ 0.70355928  0.70577383  0.70514113  0.6983918   0.69860274]]

 [[ 0.70577383  0.70514113  0.6983918   0.69860274  0.69541264]]

 [[ 0.70514113  0.6983918   0.69860274  0.69541264  0.69309253]]

 [[ 0.6983918   0.69860274  0.69541264  0.69309253  0.68847877]]

 [[ 0.69860274  0.69541264  0.69309253  0.68847877  0.69153708]]

 [[ 0.69541264  0.69309253  0.68847877  0.69153708  0.70039552]]

 [[ 0.69309253  0.68847877  0.69153708  0.70039552  0.70131826]]

 [[ 0.68847877  0.69153708  0.70039552  0.70131826  0.71117854]]

 [[ 0.6915

In [9]:
#0.60566837*1896.5  #2022

1148.6500637049999

In [10]:
#0.61117852*1896.5  #2021

1159.10006318

In [11]:
#0.60469294*1896.5  #2020

1146.80016071

In [12]:
#0.60097551*1896.5 #2019

1139.750054715

In [16]:
1165.9/1896.5      #2023

0.614764039019246

In [17]:
1173.05/1896.5     #2024

0.618534141840232

In [18]:
1178/1896.5        #2025

0.6211442130239916

In [19]:
1176.1/1896.5      #2026

0.6201423675191141

In [20]:
1183.2/1896.5      #2027

0.6238861059847087

In [24]:
testInputX =[[[ 0.59636176,  0.60097551,  0.60469294 , 0.61117852 , 0.60566837]]]
testInputX=numpy.array(testInputX)
testInputXPredict = model.predict(testInputX)

In [34]:
print testInputXPredict #2023
#[[ 0.6237635]]         #2028
#[[ 0.62435049]]         #2029
#[[ 0.62477851]]         #2030
#[[ 0.62537682]]         #2031
#[[ 0.62587976]]         #2032

[[ 0.60694778]]


In [38]:
0.6237635*1896.5
#(0.62435049-0.6237635)/0.62435049

1182.96747775

In [23]:
inputX = [[[0.614764039019246 ,0.618534141840232,0.6211442130239916,0.6201423675191141,0.6238861059847087]],
         [[0.618534141840232,0.6211442130239916,0.6201423675191141,0.6238861059847087,0.6237635]],
         [[0.6211442130239916,0.6201423675191141,0.6238861059847087,0.6237635,0.62435049]],
         [[0.6201423675191141,0.6238861059847087,0.6237635,0.62435049,0.62477851]],
         [[0.6238861059847087,0.6237635,0.62435049,0.62477851,0.62537682]]]

InputX=numpy.array(inputX)
InputXPredict = model.predict(InputX)
print InputXPredict[-1][0]

0.630429


In [4]:

#print(scaler.inverse_transform(testPredict))

# shift train predictions for plotting
trainPredictPlot = numpy.empty_like(dataset)
trainPredictPlot[:, :] = numpy.nan
trainPredictPlot[look_back:len(trainPredict)+look_back, :] = trainPredict

# shift test predictions for plotting
testPredictPlot = numpy.empty_like(dataset)
testPredictPlot[:, :] = numpy.nan
testPredictPlot[len(trainPredict)+(look_back*2)+1:len(dataset)-1, :] = testPredict

# plot baseline and predictions
plt.plot(dataset)
plt.plot(trainPredictPlot)
plt.plot(testPredictPlot)
plt.show()

In [148]:

InputX=numpy.array(inputX)
print inputX[0][0]

[0.614764039019246, 0.618534141840232, 0.6211442130239916, 0.6201423675191141, 0.6238861059847087]


In [29]:
inputX = [[[0.614764039019246 ,0.618534141840232,0.6211442130239916,0.6201423675191141,0.6238861059847087]],
         [[0.618534141840232,0.6211442130239916,0.6201423675191141,0.6238861059847087,0.6237635]],
         [[0.6211442130239916,0.6201423675191141,0.6238861059847087,0.6237635,0.62435049]],
         [[0.6201423675191141,0.6238861059847087,0.6237635,0.62435049,0.62477851]],
         [[0.6238861059847087,0.6237635,0.62435049,0.62477851,0.62537682]]]
print inputX[-1][0]

[0.6238861059847087, 0.6237635, 0.62435049, 0.62477851, 0.62537682]


In [161]:
-

1192.03703594
1199.19530717
1206.86870262
1214.96520758
1222.86807466
1230.74211648
1238.6664612
1246.56819788
1254.44585699
1262.3136816


In [140]:
temp = ()
for i in range(5):
    temp = temp + tuple([i])
print temp

temp2=tuple(inputX[-1][0])

(0, 1, 2, 3, 4)


In [141]:
plt.bar(left =temp ,height = temp2)
plt.show()

(0.62854576, 0.63232023, 0.63636631, 0.64063549, 0.64480257)

(0, 1, 2, 3, 4)
